// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_drawgame.cpp"
#include "EWIEGA46WW/moc_game.cpp"
#include "EWIEGA46WW/moc_paramofnewgame.cpp"
#include "EWIEGA46WW/moc_setiings.cpp"
#include "EWIEGA46WW/moc_symboloflife.cpp"
